### ISSUE TITLE
Cannot compile with lcms 2.16

### ISSUE THREAD

**Issue by raffaem** [JakubMelka/PDF4QT#129]
When using lcms 2.16, the following error shows up:

```
[  4%] Building CXX object Pdf4QtLibCore/CMakeFiles/Pdf4QtLibCore.dir/sources/pdfcms.cpp.o
/XXX/pdf4qt-git-pkgbuild/src/pdf4qt-git/Pdf4QtLibCore/sources/pdfcms.cpp: In static member function ‘static cmsBool pdf::PDFLittleCMS::optimizePipeline(cmsPipeline**, cmsUInt32Number, cmsUInt32Number*, cmsUInt32Number*, cmsUInt32Number*)’:
/home/raffaele/data/progetti_miei/pdf4qt-git-pkgbuild/src/pdf4qt-git/Pdf4QtLibCore/sources/pdfcms.cpp:827:58: error: ‘cmsGetToneCurveParams’ was not declared in this scope; did you mean ‘cmsGetToneCurveSegment’?
  827 |                         const cmsFloat64Number* params = cmsGetToneCurveParams(curve);
      |                                                          ^~~~~~~~~~~~~~~~~~~~~
      |                                                          cmsGetToneCurveSegment
make[2]: *** [Pdf4QtLibCore/CMakeFiles/Pdf4QtLibCore.dir/build.make:381: Pdf4QtLibCore/CMakeFiles/Pdf4QtLibCore.dir/sources/pdfcms.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:494: Pdf4QtLibCore/CMakeFiles/Pdf4QtLibCore.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

This is due to the function being removed between 2.15 and 2.16 in https://github.com/mm2/Little-CMS/commit/03020d0fdd0f8a79f275657ad1ff757fe2cc4192

The new function seems to be `cmsGetToneCurveSegment`

**Comment by raffaem** [comment]
https://github.com/mm2/Little-CMS/issues/377#issuecomment-1519100435

**Comment by JakubMelka** [comment]
Hello @raffaem, I have slightly reworked the code; it should now work properly. The dependency on the problematic function has been removed.
